import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="abox">
          <a href="/DownloadAndPrint">다운로드/프린트</a>
          <a href="/Shape">Draw</a>
          <a href="/Shape">Static</a>
        </div>

        {children}
      </body>
    </html>
  );
}
